# Import Libaries

In [3]:
!pip install numpy
import numpy as np
!pip install pandas
import pandas as pd
!pip install mysql-connector-python
import mysql.connector
from mysql.connector import Error

     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.8 kB 682.7 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.8 kB 525.1 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 404.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.9 MB 2.0 MB/s eta 0:00:07
   ---------------------------------------- 0.1/12.9 MB 1.5 MB/s eta 0:00:09
   ---------------------------------------- 0.1/12.9 MB 1.1 MB/s eta 0:00:12
    --------------------------------------- 0.2/12.9 MB 1.1 MB/s eta 0:00:13
    --------------------------------------- 0.2/12.9 MB 1.1 MB/s eta 0:00:13
    --------------------------------------- 0.2/12.9 MB 1.1 MB/s eta 0:00:13
    --------------------------------------- 0.2/12.9 MB 1.1 MB/s eta 0:00:13
    -----


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\adity\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/11.6 MB 871.5 kB/s eta 0:00:14
    --------------------------------------- 0.2/11.6 MB 1.2 MB/s eta 0:00:10
    --------------------------------------- 0.2/11.6 MB 1.2 MB/s eta 0:00:10
   - -------------------------------------- 0.4/11.6 MB 1.7 MB/s eta 0:00:07
   - -------------------------------------- 0.4/11.6 MB 1.7 MB/s eta 0:00:07
   - -------------------------------------- 0.4/11.6 MB 1.7 MB/s eta 0:00:07
   - -------------------------------------- 0.4/11.6 MB 1.7 MB/s eta 0:00:07
   - -------------------------------------- 0.4/11.6 MB 1.7 MB/s eta 0:00:07
   - ----------------------------------


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\adity\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


   ---------------------------------------- 0.0/16.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.1 MB 1.4 MB/s eta 0:00:12
   ---------------------------------------- 0.0/16.1 MB 1.4 MB/s eta 0:00:12
   ---------------------------------------- 0.1/16.1 MB 375.8 kB/s eta 0:00:43
   ---------------------------------------- 0.1/16.1 MB 512.0 kB/s eta 0:00:32
   ---------------------------------------- 0.1/16.1 MB 657.1 kB/s eta 0:00:25
    --------------------------------------- 0.2/16.1 MB 962.7 kB/s eta 0:00:17
    --------------------------------------- 0.2/16.1 MB 962.7 kB/s eta 0:00:17
    --------------------------------------- 0.3/16.1 MB 922.8 kB/s eta 0:00:18
    --------------------------------------- 0.4/16.1 MB 892.7 kB/s eta 0:00:18
   - -------------------------------------- 0.4/16.1 MB 984.2 kB/s eta 0:00:16
   - -------------------------------------- 0.4/16.1 MB 984.2 kB/s eta 0:0


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\adity\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [ ]:
# --- DATABASE CONFIGURATION ---
db_config = {
    'host': 'localhost',
    'user': 'root', 
    'password': 'root', 
    'database': 'crop_recommendation_db' # Should match the database name you created
}
# --- END OF DATABASE CONFIGURATION ---

# Importing Data

In [6]:
# --- LOAD DATA FROM MYSQL DATABASE ---
conn = None
cursor = None
crop = None
try:
    print("Attempting to connect to database...")
    conn = mysql.connector.connect(**db_config)
    if conn.is_connected():
        print('Successfully connected to MySQL database')
        cursor = conn.cursor(dictionary=True)
        query = """
        SELECT N, P, K, temperature, humidity, ph, rainfall, recommended_crop_id AS crop_num
        FROM Conditions;
        """
        print("Executing query...")
        cursor.execute(query)
        results = cursor.fetchall()
        print(f"Fetched {len(results)} rows from database.")
        if results:
             crop = pd.DataFrame(results)
             print("Converted results to Pandas DataFrame.")
        else:
             print("No data fetched from the database table 'Conditions'.")
    else:
        print("Database connection failed.")
except Error as e:
    print(f"Error connecting to MySQL or fetching data: {e}")
finally:
    if cursor: cursor.close(); print("MySQL cursor closed.")
    if conn and conn.is_connected(): conn.close(); print("MySQL connection closed.")
# --- END OF LOAD DATA FROM MYSQL ---

# --- IMPORTANT CHECK ---
if crop is None or crop.empty:
    print("\n!!! CRITICAL ERROR: Failed to load data from database. DataFrame is empty or None. Cannot proceed. Check credentials and table data. !!!")
else:
    print("\nDataFrame head loaded from Database:")
    print(crop.head()) # Display the first few rows

Attempting to connect to database...
Successfully connected to MySQL database
Executing query...
Fetched 0 rows from database.
No data fetched from the database table 'Conditions'.
MySQL cursor closed.
MySQL connection closed.

!!! CRITICAL ERROR: Failed to load data from database. DataFrame is empty or None. Cannot proceed. Check credentials and table data. !!!


In [ ]:
import mysql.connector
from mysql.connector import Error
import io

# --- DATABASE CONFIGURATION ---
db_config = {
    'host': 'localhost',
    'user': 'root',  
    'password': 'root',  
    'database': 'crop_recommendation_db'
}
# --- END OF DATABASE CONFIGURATION ---

# --- Crop Name to ID Mapping ---
# (Based on your original notebook's dictionary)
crop_name_to_id = {
    'rice': 1, 'maize': 2, 'jute': 3, 'cotton': 4, 'coconut': 5,
    'papaya': 6, 'orange': 7, 'apple': 8, 'muskmelon': 9,
    'watermelon': 10, 'grapes': 11, 'mango': 12, 'banana': 13,
    'pomegranate': 14, 'lentil': 15, 'blackgram': 16, 'mungbean': 17,
    'mothbeans': 18, 'pigeonpeas': 19, 'kidneybeans': 20, 'chickpea': 21,
    'coffee': 22
}
# --- End of Mapping ---

# --- CSV DATA ---
csv_data_string = """
90,42,43,20.87974371,82.00274423,6.502985292000001,202.9355362,rice
85,58,41,21.77046169,80.31964408,7.038096361,226.6555374,rice
60,55,44,23.00445915,82.3207629,7.840207144,263.9642476,rice
74,35,40,26.49109635,80.15836264,6.980400905,242.8640342,rice
78,42,42,20.13017482,81.60487287,7.628472891,262.7173405,rice
69,37,42,23.05804872,83.37011772,7.073453503,251.0549998,rice
69,55,38,22.70883798,82.63941394,5.70080568,271.3248604,rice
94,53,40,20.27774362,82.89408619,5.718627177999999,241.9741949,rice
89,54,38,24.51588066,83.53521629999999,6.685346424,230.4462359,rice
68,58,38,23.22397386,83.03322691,6.336253525,221.2091958,rice
91,53,40,26.52723513,81.41753846,5.386167788,264.6148697,rice
90,46,42,23.97898217,81.45061596,7.50283396,250.0832336,rice
78,58,44,26.80079604,80.88684822,5.108681786,284.4364567,rice
93,56,36,24.01497622,82.05687182,6.98435366,185.2773389,rice
94,50,37,25.66585205,80.66385045,6.94801983,209.5869708,rice
60,48,39,24.28209415,80.30025587,7.0422990689999985,231.0863347,rice
85,38,41,21.58711777,82.7883708,6.2490506560000005,276.65524589999995,rice
91,35,39,23.79391957,80.41817957,6.970859754,206.2611855,rice
77,38,36,21.8652524,80.1923008,5.953933276,224.55501690000003,rice
88,35,40,23.57943626,83.58760316,5.85393208,291.2986618000001,rice
89,45,36,21.32504158,80.47476396,6.442475375,185.4974732,rice
76,40,43,25.15745531,83.11713476,5.070175667,231.3843163,rice
67,59,41,21.94766735,80.97384195,6.012632591,213.3560921,rice
83,41,43,21.0525355,82.67839517,6.254028451,233.1075816,rice
98,47,37,23.48381344,81.33265073,7.375482851,224.0581164,rice
66,53,41,25.0756354,80.52389148,7.778915154,257.0038865,rice
97,59,43,26.35927159,84.04403589,6.2865001760000006,271.35861370000003,rice
97,50,41,24.52922681,80.54498576,7.070959995,260.2634026,rice
60,49,44,20.77576147,84.49774397,6.244841491,240.0810647,rice
84,51,35,22.30157427,80.64416466,6.043304899,197.9791215,rice
73,57,41,21.44653958,84.94375962,5.824709117,272.2017204,rice
92,35,40,22.17931888,80.33127223,6.3573893660000005,200.0882787,rice
85,37,39,24.52783742,82.73685569,6.364134967999999,224.67572310000003,rice
98,53,38,20.26707606,81.63895217,5.01450727,270.4417274,rice
88,54,44,25.7354293,83.88266234,6.149410611,233.1321372,rice
95,55,42,26.79533926,82.1480873,5.950660556,193.3473987,rice
99,57,35,26.75754171,81.17734011,5.960370061,272.29990560000005,rice
95,39,36,23.86330467,83.15250801,5.561398642,285.2493645,rice
60,43,44,21.01944696,82.95221726,7.416245107000001,298.40184710000005,rice
63,44,41,24.17298839,83.7287574,5.583370042,257.0343554,rice
62,42,36,22.78133816,82.06719137,6.430010215,248.7183228,rice
64,45,43,25.62980105,83.52842314,5.534878156,209.9001977,rice
83,60,36,25.59704938,80.14509262,6.903985986,200.834898,rice
82,40,40,23.83067496,84.81360127,6.271478837999999,298.5601175,rice
85,52,45,26.31355498,82.36698992,7.224285503,265.5355937,rice
91,35,38,24.8972823,80.52586088,6.13428721,183.6793207,rice
76,49,42,24.958779,84.47963372,5.206373153,196.95600080000003,rice
74,39,38,23.24113501,84.59201843,7.782051312999999,233.0453455,rice
79,43,39,21.66628296,80.70960551,7.062779015,210.8142087,rice
88,55,45,24.63544858,80.41363018,7.730367824,253.7202781,rice
60,36,43,23.43121862,83.06310136,5.286203711000001,219.9048349,rice
76,60,39,20.0454142,80.3477562,6.766240045,208.5810155,rice
93,56,42,23.85724032,82.22572988,7.382762603,195.0948311,rice
65,60,43,21.97199397,81.89918197,5.658169482000001,227.3637009,rice
95,52,36,26.22916897,83.83625819,5.543360237999999,286.5083725,rice
75,38,39,23.44676801,84.79352417,6.215109715,283.9338466,rice
74,54,38,25.65553461,83.47021081,7.120272972,217.3788583,rice
91,36,45,24.44345477,82.45432595,5.950647577000001,267.97619480000003,rice
71,46,40,20.2801937,82.1235421,7.236705436,191.9535738,rice
99,55,35,21.7238313,80.2389895,6.501697816,277.9626192,rice
72,40,38,20.41447029,82.20802629,7.592490617,245.1511304,rice
83,58,45,25.75528612,83.51827127,5.875345751,245.6626799,rice
93,58,38,20.61521424,83.77345559,6.932400225,279.5451717,rice
70,36,42,21.84106875,80.72886384,6.9462098810000015,202.3838319,rice
76,47,42,20.08369642,83.29114712,5.739175027000001,263.6372176,rice
99,41,36,24.45802087,82.74835604,6.738652179,182.5616319,rice
99,54,37,21.14347496,80.33502926,5.5948196260000005,198.6730942,rice
86,59,35,25.78720567,82.11124033,6.946636369,243.5120414,rice
69,46,41,23.64124821,80.28597873,5.012139669,263.1103304,rice
91,56,37,23.43191632,80.56887849,6.363472207999999,269.5039162,rice
61,52,41,24.97669518,83.891805,6.880431223,204.8001847,rice
67,45,38,22.72791041,82.17068809999998,7.300410836,260.8875056,rice
79,42,37,24.87300744,82.84022551,6.587918707999999,295.6094492000001,rice
78,43,42,21.32376327,83.00320459,7.283736617000001,192.3197536,rice
75,54,36,26.29465461,84.56919326,7.023936392,257.4914906,rice
97,36,45,22.2286982,81.85872947,6.939083505,278.0791793,rice
67,47,44,26.73072391,81.78596776,7.868474653,280.4044392,rice
73,35,38,24.88921174,81.97927117,5.005306977,185.9461429,rice
77,36,37,26.88444878,81.46033732,6.136131869,194.5766559,rice
81,41,38,22.67846116,83.72874389,7.5240800760000015,200.9133156,rice
68,57,43,26.08867875,80.37979919,5.706943251,182.9043504,rice
72,45,35,25.42977518,82.94682591,5.758506323,195.3574542,rice
61,53,43,26.40323239,81.05635517,6.349606327,223.3671883,rice
67,43,39,26.04371967,84.96907151,5.9999690260000005,186.7536773,rice
67,58,39,25.2827223,80.54372813,5.453592032,220.1156708,rice
66,60,38,22.08576562,83.47038318,6.372576327000001,231.7364957,rice
82,43,38,23.28617173,81.43321641,5.105588355,242.3170629,rice
84,50,44,25.48591986,81.40633547,5.9353444060000005,182.6549356,rice
81,53,42,23.67575393,81.03569343,5.17782304,233.7034975,rice
91,50,40,20.82477109,84.1341879,6.462391607000001,230.22422230000004,rice
93,53,38,26.92995077,81.91411159,7.069172227,290.67937830000005,rice
90,44,38,23.83509503,83.88387074,7.473134377,241.20135130000003,rice
81,45,35,26.52872817,80.12267476,6.158376967000001,218.9163567,rice
78,40,38,26.46428311,83.85642678,7.549873681,248.2256491,rice
60,51,36,22.69657794,82.81088865,6.028321557999999,256.9964761,rice
88,46,42,22.68319059,83.46358271,6.604993475,194.2651719,rice
93,47,37,21.53346343,82.14004101,6.500343222000001,295.9248796,rice
60,55,45,21.40865769,83.32931909999998,5.935745417000001,287.5766935000001,rice
78,35,44,26.54348085,84.67353597,7.072655622,183.6222657,rice
65,37,40,23.35905428,83.59512273,5.333322606,188.413665,rice
71,54,16,22.61359953,63.69070564,5.7499144210000015,87.75953857,maize
61,44,17,26.10018422,71.57476937,6.931756557999999,102.2662445,maize
80,43,16,23.55882094,71.59351368,6.657964753,66.71995467,maize
73,58,21,19.97215954,57.68272924,6.596060648,60.65171481,maize
61,38,20,18.47891261,62.69503871,5.970458434,65.43835393,maize
68,41,16,21.77689322,57.80840636,6.158830619,102.0861694,maize
93,41,17,25.6217169,66.50415474,6.047906679,105.4654703,maize
89,60,19,25.19192419,66.69029010000001,5.913664501,78.06639649,maize
76,44,17,20.41683147,62.55424820000001,5.855442401,65.27798457,maize
67,60,25,24.92162194,66.78627406,5.750254943,109.2162279,maize
70,44,19,23.31689124,73.4541537,5.852607099,94.29712821,maize
90,49,21,24.84016732,68.3584573,6.4725232870000005,74.05474936,maize
62,52,16,22.27526694,58.84015925,6.9670577620000005,63.87020584,maize
92,44,16,18.87751445,65.76816093,6.082973754,94.76189431,maize
66,54,21,25.19008683,60.200168700000006,5.919045532,72.12375573,maize
63,58,22,18.25405352,55.28220433,6.204747652999999,63.72358154,maize
70,47,17,24.612911800000006,70.4162444,6.600827017,104.1626147,maize
61,41,17,25.1420613,65.26185135,6.021902237000001,76.68456006,maize
66,53,19,23.09348056,60.11593810000001,6.033550195,65.49730729,maize
74,55,19,18.05033737,62.89366992,6.28886807,84.23613484,maize
77,57,21,24.9321581,73.80435276,6.550563822999999,79.74078719,maize
99,50,15,18.14710054,71.09445342,5.573286437,88.07753741,maize
74,56,22,18.28362235,66.65952796,6.829199275,80.97573281,maize
83,45,21,18.83344471,58.75082029,5.716222912,79.75328959999999,maize
100,48,16,25.71895816,67.22190688,5.54990242,74.51490791,maize
79,51,16,25.33797709,68.49835977,6.586244581,96.46380213,maize
94,39,18,23.89114571,57.48775781,5.893093135,102.8301942,maize
75,49,15,21.53574127,71.50905983,5.918263801,102.4852929,maize
78,48,22,23.08974909,63.10459626,5.588650585,70.43473609,maize
87,54,20,25.61707368,63.4711755,6.576418207000001,108.8303762,maize
87,35,25,21.44526922,63.1621551,6.178056304,65.88951188,maize
63,43,19,18.51816776,55.53128131,6.641906353,90.988051,maize
84,57,25,22.53510514,67.99257471,6.489040367,64.40866039,maize
64,35,23,23.02038334,61.89472002,5.680361037999999,63.03843397,maize
60,46,22,24.89364635,65.61418761,6.625404347999999,87.9298085,maize
98,44,21,25.77175115,74.089114,6.524478032,107.4931917,maize
75,56,18,19.39851734,62.35750641,5.696205468,60.95197486,maize
86,55,21,21.54156232,59.64024162,6.803931519,109.7515385,maize
98,35,18,23.79746068,74.82913698,6.252797547999999,91.76337172,maize
76,57,18,18.9802729,74.52600826,6.092725883,94.26249353,maize
99,56,17,24.10859207,73.13112261,6.234330356,71.07562236,maize
60,44,23,24.7947077,70.04556743,5.722579819,76.72860067,maize
74,48,17,21.63162756,60.27766379,6.430616465,69.21803098,maize
89,60,17,25.37548751,57.21025565,5.983952675,101.7004306,maize
69,51,23,22.21738222,72.85462807,6.80163854,106.6213157,maize
96,46,22,20.58314011,69.00128641,6.499936446,66.29390357,maize
61,60,15,24.87502824,68.74248334,6.265564338,91.26056654,maize
74,58,18,20.03728219,56.35606753,6.727303282,109.024141,maize
74,43,23,25.95263264,61.89082199,6.325235159,99.57981207,maize
63,43,17,19.28889933,65.47050802,6.807487794,71.3195307,maize
99,36,20,20.57981887,65.34583901,6.671085817000001,78.34604471,maize
77,36,23,24.71417533,56.73426469,6.648725327,88.45361858,maize
87,60,23,20.27317074,63.91281869,6.439071996,62.50351892,maize
60,38,17,18.41932981,64.23580251,6.474476516,76.41312437,maize
94,54,17,23.39128187,61.74427165,5.871647806,107.3198135,maize
95,38,22,19.84939404,61.24500053,5.730617109,100.7689246,maize
84,44,21,21.869274,61.91044947,5.850439831,107.2681929,maize
77,58,19,22.8056033,56.50768935,5.791649933,101.5952794,maize
66,44,20,19.0781471,69.02298571,6.740000687999999,80.72515943,maize
63,35,16,22.02720976,65.35549924,6.272417541,83.73280082,maize
79,45,20,23.80546189,59.24537979,5.715208817000001,89.96220140000001,maize
72,60,25,18.52510753,69.0276233,5.773454729,88.10234397,maize
67,51,24,23.50297882,61.32026065,5.584171461,64.77791424,maize
86,36,24,26.54986394,72.89187265,5.787268394,73.33636055,maize
76,48,18,19.29563411,69.63481219,5.77597783,83.21030571,maize
75,53,18,20.68899915,59.4375337,6.864793607,103.651438,maize
81,45,23,19.32666088,68.03449300000001,6.192360002999999,84.22969177,maize
73,45,21,24.60532218,73.58868502,6.636803222999999,96.59195302,maize
71,35,24,22.27373646,59.52193158,5.826426917,67.96704792,maize
96,54,22,25.70196694,61.33450447,6.960358276,83.20711308,maize
99,39,18,19.20129357,68.30578978,6.11275104,87.85092352,maize
62,48,20,21.70181447,60.47470519,6.708446922,95.71388473,maize
86,37,16,20.51716779,59.21235483,5.561510732,67.61013737,maize
94,50,19,23.30355338,73.62548442,5.873242491,97.59081274,maize
76,39,24,24.2547451,55.64709899,6.995843776,64.23845455,maize
77,52,17,24.86374934,65.7420046,5.714799723,75.82270467,maize
74,39,23,22.6265115,65.77472881,6.78073637,88.17251033,maize
81,49,20,18.04185513,60.61494304,5.513697923,104.2321615,maize
63,42,21,23.26237612,72.33125523,5.798423907999999,67.10225139,maize
99,38,21,22.88330922,71.59722446,6.352471866,67.72777298,maize
90,52,25,25.97482359,69.36385721,6.822586546,103.2234212,maize
68,40,19,26.14384005,66.20569924,6.655426355,107.2361366,maize
60,57,24,18.66116213,61.55327249,6.1212940410000005,75.03247667,maize
71,52,18,25.10787449,55.97732754,5.790770202999999,78.16077693,maize
61,59,17,23.33844615,59.24580604,6.47444292,105.0083144,maize
88,38,15,25.08239719,65.92195844,6.455116637000001,62.49190812,maize
65,60,22,25.36768364,72.52054555,6.6069840860000015,107.9124111,maize
78,37,22,25.34217103,63.31801994,6.330554389,74.52082026,maize
78,58,15,25.00933355,67.816568,6.5286312660000005,62.91359494,maize
92,60,23,18.66746724,71.516474,5.721667141,69.93293255,maize
79,59,17,20.37999665,63.73849998,6.644205485,108.5054416,maize
91,55,15,18.09300227,72.61024172,6.376651091,78.96159541,maize
76,51,18,26.16985907,71.96246617,6.247040422,79.84925393,maize
87,48,25,18.65396672,61.37879671,6.656730007999999,93.62039175,maize
71,60,22,26.07470121,59.37147589,6.2048017,85.75692395,maize
90,57,24,18.92851916,72.80086137,6.158860284,82.34162918,maize
67,35,22,23.30546753,63.24648023,6.3856842139999985,108.7603001,maize
60,54,19,18.74826712,62.49878458,6.417820493,70.23401597,maize
83,58,23,19.74213321,59.66263104,6.381201909,65.50861389,maize
83,57,19,25.73044432,70.74739256,6.877869005,98.73771338,maize
40,72,77,17.02498456,16.98861173,7.485996067,88.55123143,chickpea
23,72,84,19.02061277,17.13159126,6.920251378,79.92698081,chickpea
39,58,85,17.88776475,15.40589717,5.9969320370000005,68.54932919,chickpea
22,72,85,18.86805647,15.65809214,6.391173589,88.51048983,chickpea
36,67,77,18.36952567,19.56381041,7.152811172000001,79.26357665,chickpea
32,73,81,20.45078582,15.40312102,5.988992796000002,92.68373702,chickpea
58,70,84,20.6543203,16.60820843,6.231049027999999,74.6631118,chickpea
59,70,84,17.3348681,18.74926979,7.550808267000001,82.61734721,chickpea
42,62,75,18.17912258,18.90426935,7.010570541,81.84997529,chickpea
28,74,81,18.01272266,18.30968112,8.753795334,81.98568791,chickpea
58,66,79,20.99373558,19.33470387,8.718192847000001,93.55280105,chickpea
43,66,79,19.46233971,15.22538951,7.976607593,74.58565097,chickpea
58,63,81,19.81344531,14.69765308,6.5154995489999985,78.96514709,chickpea
23,62,85,18.97424756,19.5161216,8.490127142,80.7108745,chickpea
27,62,77,18.19737048,14.71070537,6.576415562,70.18185181,chickpea
28,72,84,18.72963144,19.18197264,6.481783042999999,71.58010169,chickpea
50,56,76,20.99502153,19.8601304,7.966605025,73.50734019,chickpea
39,71,84,20.28155898,16.39535215,8.140825437,82.52339655,chickpea
25,78,76,17.48042641,15.7559405,7.228963452,66.96980581,chickpea
31,70,77,20.88818675,14.32313811,6.492546046,90.46228334,chickpea
26,80,83,17.08498521,16.14565756,7.528599957000001,71.31007253,chickpea
25,68,77,20.09340593,15.11279612,7.701446446,85.74904898,chickpea
31,78,76,17.57212145,14.99927489,8.519975748,89.31050665,chickpea
60,68,83,19.12065218,18.43475844,6.620900869,85.52950164,chickpea
59,62,83,18.57665902,19.22008229,8.104396057999999,72.94940441,chickpea
22,67,78,17.16606398,14.42457525,6.204090835,72.32667516,chickpea
36,65,80,18.2872007,16.67921616,6.051091339,74.87445574,chickpea
59,60,84,19.03025305,18.66725565,7.690962337999999,94.70992037,chickpea
54,77,85,17.141861399999996,17.0662427,7.8292111439999985,83.74606679,chickpea
43,68,81,17.47809436,17.93253975,6.761599706,78.92060234,chickpea
28,76,82,20.56601874,14.25803981,6.654425315,83.75937135,chickpea
42,79,85,17.22385224,15.82069268,6.129533877,76.57580954,chickpea
32,60,83,19.69141713,19.44225438,8.829273328,91.76071648,chickpea
22,78,76,17.84851658,19.09172907,8.621662982,76.32470713,chickpea
31,79,75,18.8202251,16.1074793,8.204862075,89.73119396,chickpea
28,58,81,17.47500984,16.54314829,6.18042747,93.35034262,chickpea
57,58,77,18.72649425,17.58406365,7.978996755,81.20176515,chickpea
49,55,78,18.65580107,16.17772668,7.863113671,81.70769297,chickpea
46,76,77,18.2356751,19.68538502,6.967843048,83.74879344,chickpea
54,61,77,18.81198127,15.21618225,6.206582192999999,77.54294240000002,chickpea
38,60,76,18.65054116,17.80852431,8.868741443,77.92798682,chickpea
59,55,79,20.36720401,16.89574311,8.766128654,82.2545577,chickpea
36,76,75,18.38120357,16.63805158,8.736337905,70.52056697,chickpea
57,68,81,17.17012591,17.30457712,8.081095263,72.78624223,chickpea
35,66,81,19.37101121,15.77458129,6.138243973,85.24819851,chickpea
35,64,78,17.92845928,14.27327988,7.496645259,85.37378769,chickpea
52,60,79,19.45339934,18.23490739,8.380185271,75.6317566,chickpea
27,76,83,19.12829388,14.92241479,6.289614016,89.61857826,chickpea
57,60,84,19.1034283,17.26184541,6.586777189,75.49101167,chickpea
52,68,78,17.48504075,16.96070581,6.89655198,86.05078037,chickpea
43,79,79,19.40751744,18.98030507,7.8067476560000015,80.25064637,chickpea
44,74,85,20.18649426,19.63719995,7.150681303,78.26039559,chickpea
24,55,78,17.30287885,15.15405941,6.64919573,75.57790384,chickpea
29,77,75,17.50361137,15.48083156,7.778591617999999,72.9446671,chickpea
20,60,78,18.17234999,14.70085967,6.358740355,90.7760707,chickpea
56,67,78,17.57445618,16.71826572,8.255450758,77.81891424,chickpea
37,66,85,20.93175255,18.91295403,6.456148474,78.06910795,chickpea
49,71,76,19.71098332,17.63879418,6.613072145,85.57925437,chickpea
59,69,80,19.07937684,17.86754927,8.165359297,69.40619137,chickpea
20,79,77,18.54988627,16.02542689,7.64867466,76.32565249,chickpea
24,56,85,18.19903647,17.41333199,6.545888558,80.6405403,chickpea
51,72,75,18.88852533,14.99451145,7.1042247970000005,80.11133840000002,chickpea
57,73,85,18.49311205,14.72115044,7.358099622,91.94595352,chickpea
22,64,82,19.48974337,17.17260319,6.4740245000000005,87.51312796,chickpea
52,73,79,17.25769499,18.74943955,7.840339388999999,94.00287214,chickpea
29,75,75,19.62416326,18.71483156,7.064790365,88.4585692,chickpea
44,59,78,20.67526473,19.85388984,7.599033472,84.78344008,chickpea
41,69,82,20.02381489,16.63294455,6.715587232000001,68.97806542,chickpea
52,56,85,20.118744600000007,14.44228303,6.81712422,88.68168643,chickpea
34,76,80,20.65691793,15.84572566,7.985417393,65.23811143,chickpea
42,74,83,19.2582557,14.2804191,7.545258424,65.78042032,chickpea
34,71,79,17.927806,15.85622899,7.728998197,74.63872762,chickpea
27,73,79,19.16288268,15.83500655,7.354973451,82.69766829,chickpea
30,70,79,20.26942271,19.96978871,7.313122235,69.64449182,chickpea
57,57,75,17.09104223,18.25142068,7.785039076,87.27444866,chickpea
27,79,82,17.06579293,17.54024066,6.307004922999999,70.87150577,chickpea
32,71,85,20.62767492,14.44008871,6.4039823160000005,92.06630306,chickpea
31,76,82,20.8248451,17.85057083,7.599279991,79.20509212,chickpea
33,75,84,19.46210401,18.72831993,7.217018459,68.81405149,chickpea
47,80,77,17.18248372,16.42891834,7.561108006,72.85017344,chickpea
54,62,80,17.48911699,16.39055394,7.489545074,79.45758333,chickpea
47,79,78,17.48395377,14.76014523,6.609696734,65.11365631,chickpea
35,57,83,19.48316794,17.44534641,7.476800943,80.4986291,chickpea
53,73,77,19.71359733,18.09665739,7.325451279,73.64476535,chickpea
45,61,78,19.48649305,16.06240074,6.489389282,81.52842690000001,chickpea
37,78,79,19.95264829,14.82633099,7.786366322,88.6810311,chickpea
30,75,81,19.41789736,16.80472243,6.4084378860000015,68.4951189,chickpea
37,55,82,19.45591848,18.02235902,8.423873703,78.44910564,chickpea
53,65,76,20.19137759,16.41998269,8.719960893,77.33795356,chickpea
22,60,85,18.8392908,14.74071856,7.811997977000001,94.78189594,chickpea
60,61,78,20.71219282,19.83643308,6.317153205,94.03659867,chickpea
42,67,77,18.99424448,15.9362937,7.114405288,78.69707199,chickpea
39,76,76,19.96837462,15.57324389,8.135900726000001,69.15759062,chickpea
35,63,76,17.81564548,17.60756635,7.714153037999999,90.82097601,chickpea
30,65,82,20.71424384,15.27824066,7.103798069,76.77888672,chickpea
57,56,78,17.34150229,18.75626255,8.861479668,67.9545435,chickpea
48,65,78,17.43732714,14.33847406,7.861128148,73.0926704,chickpea
36,56,83,18.89780215,19.76182946,7.4526709,69.09512477,chickpea
40,58,75,18.59190771,14.77959596,7.168096055,89.60982451,chickpea
49,69,82,18.31561493,15.36143547,7.26311855,81.78710463,chickpea
13,60,25,17.13692774,20.59541693,5.68597166,128.256862,kidneybeans
25,70,16,19.63474332,18.90705639,5.759237003,106.3598183,kidneybeans
31,55,22,22.91350245,21.33953114,5.873171894,109.225556,kidneybeans
40,64,16,16.43340342,24.24045875,5.926676985,140.3717815,kidneybeans
2,61,20,22.13974653,23.02251117,5.95561668,76.64128258,kidneybeans
26,65,22,17.84806561,18.77621951,5.9499490810000015,143.09841709999995,kidneybeans
17,57,21,19.88394011,20.31564139,5.7892142889999985,60.91974792,kidneybeans
26,80,18,19.32509638,23.3334788,5.581021521,104.7783947,kidneybeans
17,59,17,18.416700100000003,23.42829938,5.689858133,132.9801054,kidneybeans
27,59,22,21.81167649,23.20591245,5.7941585039999985,130.0608093,kidneybeans
28,58,24,19.72702528,18.28173015,5.748190462999999,143.7630894,kidneybeans
25,57,19,17.15432954,19.87070659,5.566522896,87.99669731,kidneybeans
28,80,17,19.62207826,18.67170854,5.809419584,144.1567454,kidneybeans
25,60,22,21.63149148,21.17919701,5.887263027,134.3649948,kidneybeans
12,78,23,16.06522754,18.72479695,5.99812453,88.06638775,kidneybeans
6,77,25,20.61162204,24.36314135,5.792744849,69.63833855,kidneybeans
22,79,17,21.42451099,20.39659714,5.912289889,116.5206923,kidneybeans
27,80,15,19.07096165,21.21092266,5.7883869510000014,86.21917578,kidneybeans
10,55,23,21.18853178,19.63438599,5.728233081,137.1948633,kidneybeans
23,65,20,23.0429097,22.42610972,5.833940084,108.3684316,kidneybeans
19,78,16,20.65375833,23.10538637,5.967533236,67.71768947,kidneybeans
19,65,25,18.09551014,18.29318436,5.6250964460000015,144.7902323,kidneybeans
22,70,19,18.23775702,21.07643273,5.515615023,69.44951585,kidneybeans
37,64,22,17.48189735,18.8251973,5.954665349,121.9401369,kidneybeans
11,71,17,19.9191786,21.47324158,5.74644777,82.68554379,kidneybeans
18,79,20,20.27514686,23.2353604,5.877347515,139.7521543,kidneybeans
21,63,17,15.77370214,19.2303162,5.979973965,108.3441414,kidneybeans
24,80,22,16.71170642,19.17651433,5.635993966,96.77285817,kidneybeans
34,60,22,17.66148158,18.15302753,5.635231778,100.6711761,kidneybeans
16,75,21,18.50692825,23.61670065,5.679224346,87.05132890000002,kidneybeans
17,77,23,24.51324787,20.81527638,5.670062975,64.19497947,kidneybeans
37,72,18,18.87614998,24.54038287,5.724242065,105.4120514,kidneybeans
40,73,20,21.59343016,20.31871249,5.811314232000001,61.13872036,kidneybeans
9,77,17,20.12373284,24.45202552,5.783425416,106.158201,kidneybeans
1,62,23,15.43546065,18.37477907,5.607808432000001,139.0302034,kidneybeans
33,59,22,22.64236876,21.59396123,5.946999529,122.3886015,kidneybeans
23,59,19,21.98560799,24.87304788,5.852046999,129.5650601,kidneybeans
6,62,22,20.53052663,18.09224048,5.824090984,120.4509288,kidneybeans
25,63,20,15.78601387,21.14544088,5.502999119,95.17028129,kidneybeans
7,79,23,19.6365349,19.68751084,5.821649914,96.65888933,kidneybeans
8,72,17,20.57341244,19.7520218,5.711439256,87.87869161,kidneybeans
27,64,15,20.16080524,24.84207559,5.514927264,138.2362122,kidneybeans
28,66,23,21.53989176,24.25386207,5.99616119,120.6913038,kidneybeans
32,57,18,15.53834801,23.75560241,5.695422862999999,107.3850593,kidneybeans
27,56,22,19.91853092,20.70099804,5.833010957999999,108.6434544,kidneybeans
17,77,24,20.76952209,18.93146941,5.568456899,109.0193712,kidneybeans
0,65,15,23.46168338,23.22197648,5.645435626,95.84253438,kidneybeans
13,72,21,24.32116642,21.0278674,5.821194486,60.27552528,kidneybeans
34,60,23,20.12574053,24.96969858,5.659254981,100.0497183,kidneybeans
9,80,19,21.80619564,18.57086554,5.945465949,125.0972687,kidneybeans
11,72,20,19.52226241,24.92607153,5.9511774520000005,113.334026,kidneybeans
3,67,24,17.00067625,19.90790546,5.5208800139999985,103.2926407,kidneybeans
35,69,23,16.78791503,24.96881755,5.578410206,75.45328039,kidneybeans
3,77,25,24.84906168,22.89464642,5.608165195,62.21292186,kidneybeans
23,62,19,16.51783455,20.4555596,5.609435127999999,98.77794225,kidneybeans
22,71,17,18.15300153,19.38602098,5.509295379,107.6907964,kidneybeans
31,79,25,23.18864385,22.3104551,5.902033406,63.38208822,kidneybeans
34,59,18,23.38002569,21.98879437,5.744117663,87.66898664,kidneybeans
12,63,17,18.358923,19.37703396,5.717143397,138.414764,kidneybeans
27,56,20,19.25975367,20.51346956,5.542690119,94.9533526,kidneybeans
7,63,24,22.95458237,24.03553105,5.858617867,107.7315386,kidneybeans
24,67,22,20.120043,22.89845607,5.618844277000001,104.6252153,kidneybeans
11,71,24,21.14011423,22.7182355,5.6066203460000015,141.6056722,kidneybeans
37,74,15,24.92360104,18.22590825,5.582178402,62.7089169,kidneybeans
25,76,24,15.33042636,24.91506728,5.56503533,135.3315583,kidneybeans
34,66,17,18.81097271,21.27833035,5.889614577000001,125.084915,kidneybeans
20,69,15,23.44260668,22.77255917,5.934136378,107.4137246,kidneybeans
37,65,16,22.8352024,18.97267518,5.683548308,63.59276673,kidneybeans
18,74,15,24.9035819,22.27512704,5.70836603,146.4727237,kidneybeans
4,67,25,23.78709569,24.35679348,5.948164454,119.6404412,kidneybeans
37,56,25,22.05592283,19.60379304,5.7747551439999985,126.7265372,kidneybeans
5,59,15,18.87492997,20.18238348,5.97229163,134.1811718,kidneybeans
11,61,21,18.62328774,23.02410338,5.532100554,135.33780330000002,kidneybeans
22,80,20,23.00884744,18.86880997,5.669560726,100.118612,kidneybeans
12,61,19,19.33162606,24.13995025,5.655726817000001,68.51253427,kidneybeans
5,74,21,16.24469193,21.35793891,5.5917040139999985,66.97053257,kidneybeans
27,69,22,17.91652287,24.90814655,5.932323085,69.14681022,kidneybeans
31,75,18,15.46789263,21.43780702,5.8242083089999985,88.88796102,kidneybeans
36,68,20,17.06104474,23.77201471,5.86442953,81.83420522,kidneybeans
5,65,16,21.32776028,18.48522915,5.866744372,109.1013261,kidneybeans
32,79,15,23.90910104,20.74619325,5.706198621,81.60211243,kidneybeans
11,78,22,23.89756791,22.74378977,5.940546818,112.6616435,kidneybeans
0,55,22,22.98666928,20.57940608,5.916779289,143.85849380000005,kidneybeans
14,59,15,21.35135729,22.91244883,5.779090476,146.4548645,kidneybeans
29,68,23,24.1638445,19.27907819,5.82738029,116.7324324,kidneybeans
32,68,19,24.62835037,18.18325169,5.514234138,149.7441028,kidneybeans
17,64,17,21.02213209,24.93896255,5.662699104,124.6118471,kidneybeans
13,69,19,17.30844532,20.01730914,5.86390397,115.199245,kidneybeans
14,67,22,23.82576704,24.75485098,5.624690247999999,84.64143632,kidneybeans
9,69,20,19.30607278,23.96362799,5.591560999,129.3449326,kidneybeans
20,73,22,16.03768615,22.33195853,5.976312537999999,130.3900798,kidneybeans
40,78,20,19.18572809,20.83398341,5.669236258,80.15293435,kidneybeans
27,72,23,19.92889503,21.79992115,5.961934481,64.02640797,kidneybeans
14,67,15,19.56376468,24.67385131,5.690065688,139.2921004,kidneybeans
7,56,18,18.31357543,24.32991649,5.698371311,76.14153904,kidneybeans
27,65,18,20.10993761,23.22323766,5.59503163,73.36386477,kidneybeans
30,63,16,23.60506572,21.90539577,5.5259045260000015,100.5978728,kidneybeans
37,70,25,19.73136909,24.89487354,5.819403771,84.06354115,kidneybeans
27,63,19,20.93409877,21.1893007,5.562201934,133.1914419,kidneybeans
22,60,24,18.78226261,20.24768314,5.630664753,104.2570723,kidneybeans
3,69,19,25.74679443,40.7192594,4.820788186000001,32.67891866,mothbeans
22,59,23,27.32220619,51.27868781,4.371745575,36.5037914,mothbeans
36,58,25,28.66024187,59.3189118,8.399135957999999,36.92629678,mothbeans
4,43,18,29.02955344,61.09387478,8.840656256,72.98016599,mothbeans
29,54,16,27.78031515,54.65030015,8.153022903,32.05025323,mothbeans
32,43,22,31.99928579,54.1077461,5.270749441,71.6266696,mothbeans
14,55,15,27.33580911,55.27755933,8.050304395,73.44775287,mothbeans
5,35,20,28.92952635,53.57014709,9.679240873,66.35634104,mothbeans
25,57,24,27.65472156,58.59986279,6.974978386,36.94255012,mothbeans
11,53,24,28.52396666,55.77264351,7.39389918,61.32935611,mothbeans
40,49,17,31.02215872,45.89239456,6.68727523,53.56783314,mothbeans
38,56,25,25.74095321,45.38497051,7.88118645,67.43488235,mothbeans
27,43,23,31.70447482,56.85420099,5.875333778,44.94317432,mothbeans
24,38,22,24.47876451,58.51663927,8.202706015,34.96933295,mothbeans
23,45,21,31.46511256,51.79939437,8.985348193,74.44330654,mothbeans
29,57,20,25.60973447,50.7330069,5.87707519,53.39249517,mothbeans
31,35,23,30.30260453,47.18283631,7.707595055,68.04039813,mothbeans
0,55,25,28.17489437,43.6672299,4.524171562,45.78172762,mothbeans
7,45,22,25.50634557,44.8302551,9.926212291,74.32635105,mothbeans
17,58,25,31.12896766,43.58788762,6.455592696,32.76742894,mothbeans
11,44,17,26.34043268,55.59160391,8.016210782,35.1051197,mothbeans
22,49,22,28.23494706,61.5620517,3.71105919,72.66666443,mothbeans
9,51,19,27.04453473,49.32609633,5.49091063,48.25207759,mothbeans
28,48,15,25.16125354,55.25435777,9.254089438,40.89732789,mothbeans
26,50,19,27.3179125,51.66921088,6.005242945,32.55919573,mothbeans
36,56,20,25.4123765,49.66474269,7.437078236,31.87416982,mothbeans
8,60,18,31.21629982,46.01868196,3.808429173,53.1205277,mothbeans
24,37,21,30.573999,58.22686794,5.818219385,62.74803826,mothbeans
22,43,24,25.42517036,53.22082660000001,4.52363558,46.19374559,mothbeans
36,43,24,27.09400578,43.65305437,3.510404312,41.53749535,mothbeans
22,44,24,24.30935081,56.32938343,6.030447288,58.99536268,mothbeans
17,43,22,30.06142622,45.90067655,5.498340807999999,41.0550915,mothbeans
8,45,15,28.09568993,60.98353839999999,4.61136408,33.84110759,mothbeans
7,56,23,26.33908791,40.00933429,5.545219232000001,55.50429227,mothbeans
36,57,16,28.61409059,57.14218792,8.292875733999999,57.02891698,mothbeans
11,45,19,28.70012137,44.359648,3.828031463,44.11622138,mothbeans
6,36,22,24.21610338,59.79236306,8.869532817,42.24783476,mothbeans
17,57,20,28.50677929,45.20094476,3.793575185,66.1761456,mothbeans
4,47,20,25.97948991,64.95585424,4.193189124,72.19245835,mothbeans
9,49,16,30.88482722,41.36561835,7.661537347999999,55.053805,mothbeans
25,51,24,25.5042419,61.66852372,9.392694614,65.07981523,mothbeans
36,44,21,25.12528913,51.33189406,4.516154055,38.48678973,mothbeans
21,38,20,27.10508014,63.56791363,5.794289715,62.20279647,mothbeans
37,57,20,31.1006247,44.82069159,7.354286985,70.79934452,mothbeans
32,48,18,26.45707778,56.40226277,5.993513566,64.16167699,mothbeans
29,44,20,30.04132304,63.56222995,8.620107545,31.83192392,mothbeans
25,51,18,27.77799528,54.82130787,9.45949344,50.28438729,mothbeans
10,44,24,30.99256944,43.02151392,8.0344125,58.27600682,mothbeans
23,35,18,26.4908332,47.36534833,5.414492777,36.99362831,mothbeans
9,60,23,31.96987867,57.17377029,6.2760043360000015,64.25520357,mothbeans
3,58,21,25.36140526,46.82652785,9.160691747000001,55.60523179,mothbeans
22,42,22,25.54249137,56.96640758,7.887658711,48.46797044,mothbeans
12,39,21,28.99319096,62.85948245,8.183844843,70.4713043,mothbeans
39,36,22,29.34317422,60.50320928,9.072011412,34.03335472,mothbeans
32,41,16,28.63618921,61.39451307,7.702287236,68.54877876,mothbeans
30,41,15,24.83206631,44.17085032,5.88509677,52.0810886,mothbeans
19,36,22,25.44689075,58.55363573,6.16496284,57.04826619,mothbeans
4,46,15,31.01274943,62.40392519,3.504752314,63.77192383,mothbeans
21,39,20,27.06179658,52.3003173,7.388007482999999,60.74583498,mothbeans
35,57,25,27.0956288,42.26206161,8.340398059,71.12710390000002,mothbeans
22,55,24,28.56800579,57.30636014,8.66077954,64.53027638,mothbeans
35,51,17,28.79929247,49.84213387,3.558822825,40.85534718,mothbeans
17,56,17,27.94293692,45.41393636,5.9565851,69.66289997,mothbeans
28,57,17,30.47757686,61.58245338,9.416003106,61.86633917,mothbeans
22,36,16,30.58139475,50.77148138,8.18422855,64.58559639,mothbeans
11,41,19,26.85911286,41.81420849,5.131779302,44.13827124,mothbeans
38,38,18,26.31051759,61.18749126,6.294130312999999,35.73403813,mothbeans
23,37,24,28.77833449,44.2252605,7.991902443,33.95825723,mothbeans
25,35,20,28.90245417,43.35365671,8.923095695,71.90018566,mothbeans
40,45,20,29.37687468,57.69622912,6.878498176,38.34303462,mothbeans
23,58,19,24.17093241,58.25204566,5.243634848999999,59.18953429,mothbeans
2,56,23,26.65333029,59.79023382,7.550090941,36.91852635,mothbeans
3,56,17,28.19912143,53.50567601,8.709291687999999,52.13580529,mothbeans
26,51,25,28.76488954,52.62741529,7.792508067999999,55.21606732,mothbeans
39,42,20,29.3499706,61.25353851,8.055908857999999,40.82840673,mothbeans
27,59,20,28.00937423,52.60950014,4.397698806,36.01203025,mothbeans
24,45,19,26.85851927,48.8246387,5.9523849570000005,34.7426459,mothbeans
7,40,17,31.2123945,40.92604945,8.532078732999999,53.78769958,mothbeans
15,45,23,24.20422636,61.43378674,7.224193642,46.0203959,mothbeans
26,52,23,29.98835437,49.60384796,4.931890506,52.92929636,mothbeans
20,45,16,29.93964907,54.61813464,4.626212446,45.43669946,mothbeans
34,54,24,31.2119298,41.55934359,5.026003659,68.80141783,mothbeans
19,51,25,26.80474415,48.23991436,3.5253661,43.87801983,mothbeans
29,41,21,31.49398069,62.84916863,8.86979671,64.56807592,mothbeans
20,50,22,30.99694676,46.42693735,9.406887532999999,38.31597852,mothbeans
11,40,23,29.61253065,63.04749127,5.80428611,50.1978269,mothbeans
15,54,15,29.97604322,57.03184356,8.35495812,44.86052932,mothbeans
35,55,22,30.88883074,52.62696801,8.634929739,55.51932414,mothbeans
9,59,25,30.39321309,60.16299493,7.699200949,35.37493212,mothbeans
40,45,18,30.43683729,55.20522037,5.261285926,30.92014047,mothbeans
35,38,19,25.32688786,63.18180319,9.112771682,32.71129281,mothbeans
14,58,17,30.53684308,59.96664731,4.605700542,33.48919022,mothbeans
40,55,18,30.38257873,40.5926071,7.115994051,47.95406479,mothbeans
18,36,23,24.01825377,53.76623369,7.214078621,35.03404425,mothbeans
35,52,15,28.69841277,61.14754363,9.93509073,65.67591794,mothbeans
4,59,22,29.33743412,49.00323081,8.914074888,42.44054315,mothbeans
22,51,16,27.96583691,61.34900107,8.639586199,70.10472076,mothbeans
33,47,17,24.86803974,48.27531965,8.621514073,63.9187654,mothbeans
2,51,17,25.87682261,45.96341933,5.838508699,38.53254678,mothbeans
16,51,21,31.01963639,49.97675220000001,3.532008668,32.81296548,mothbeans
"""
# --- END OF CSV DATA ---

conn = None
cursor = None
inserted_count = 0
skipped_count = 0

try:
    print("Connecting to the MySQL database...")
    conn = mysql.connector.connect(**db_config)
    cursor = conn.cursor()
    print("Connection successful.")

    # Prepare the INSERT statement
    sql_insert_query = """
    INSERT INTO Conditions (N, P, K, temperature, humidity, ph, rainfall, recommended_crop_id)
    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
    """
    
    data_io = io.StringIO(csv_data_string)

    line_num = 0
    for line in data_io:
        line_num += 1
        line = line.strip() # Remove leading/trailing whitespace
        if not line: # Skip empty lines
            continue

        values = line.split(',')
        if len(values) != 8:
            print(f"Warning: Skipping malformed line {line_num}: Incorrect number of values ({len(values)}). Line content: '{line}'")
            skipped_count += 1
            continue

        try:
            # Extract and convert values
            n_val = int(values[0].strip())
            p_val = int(values[1].strip())
            k_val = int(values[2].strip())
            temp_val = float(values[3].strip())
            hum_val = float(values[4].strip())
            ph_val = float(values[5].strip())
            rain_val = float(values[6].strip())
            crop_name = values[7].strip().lower() # Ensure lowercase for matching

            # Get crop ID from dictionary
            crop_id = crop_name_to_id.get(crop_name)

            if crop_id is None:
                print(f"Warning: Skipping line {line_num}: Crop name '{crop_name}' not found in mapping dictionary. Line content: '{line}'")
                skipped_count += 1
                continue

            # Create tuple for insertion
            insert_tuple = (n_val, p_val, k_val, temp_val, hum_val, ph_val, rain_val, crop_id)

            # Execute the insert query
            cursor.execute(sql_insert_query, insert_tuple)
            inserted_count += 1

            # Optional: Print progress every N rows
            if inserted_count % 100 == 0:
                print(f"Inserted {inserted_count} rows...")

        except ValueError as ve:
            print(f"Warning: Skipping line {line_num} due to data conversion error: {ve}. Line content: '{line}'")
            skipped_count += 1
        except Exception as e:
            print(f"Warning: Skipping line {line_num} due to unexpected error: {e}. Line content: '{line}'")
            skipped_count += 1


    # Commit the changes to the database
    conn.commit()
    print(f"\nSuccessfully inserted {inserted_count} rows.")
    if skipped_count > 0:
        print(f"Skipped {skipped_count} rows due to errors.")

except Error as e:
    print(f"Error connecting to MySQL or during insertion: {e}")
    if conn:
        print("Rolling back changes...")
        conn.rollback() # Rollback changes if error occurs during transaction

finally:
    # Close cursor and connection
    if cursor:
        cursor.close()
        print("MySQL cursor closed.")
    if conn and conn.is_connected():
        conn.close()
        print("MySQL connection closed.")

Connecting to the MySQL database...
Connection successful.
Inserted 100 rows...
Inserted 200 rows...
Inserted 300 rows...
Inserted 400 rows...
Inserted 500 rows...

Successfully inserted 500 rows.
MySQL cursor closed.
MySQL connection closed.


In [12]:

# --- LOAD DATA FROM MYSQL DATABASE ---
conn = None
cursor = None
crop = None
try:
    print("Attempting to connect to database for analysis...")
    conn = mysql.connector.connect(**db_config)
    if conn.is_connected():
        print('Successfully connected to MySQL database')
        cursor = conn.cursor(dictionary=True)
        # Query fetches exactly what your original CSV provided, plus the crop_num
        query = """
        SELECT N, P, K, temperature, humidity, ph, rainfall, recommended_crop_id AS crop_num
        FROM Conditions;
        """
        print("Executing query to fetch data...")
        cursor.execute(query)
        results = cursor.fetchall()
        print(f"Fetched {len(results)} rows from database.")
        if results:
             crop = pd.DataFrame(results)
             print("Converted results to Pandas DataFrame.")
        else:
             print("No data fetched from the database table 'Conditions'.")
    else:
        print("Database connection failed.")
except Error as e:
    print(f"Error connecting to MySQL or fetching data: {e}")
finally:
    if cursor: cursor.close(); print("MySQL cursor closed.")
    if conn and conn.is_connected(): conn.close(); print("MySQL connection closed.")
# --- END OF LOAD DATA FROM MYSQL ---

# --- IMPORTANT CHECK ---
if crop is None or crop.empty:
    print("\n!!! CRITICAL ERROR: Failed to load data from database for analysis. Cannot proceed. !!!")
    # Stop execution or raise error
    raise ValueError("Could not load data from database.")
else:
    print("\nDataFrame head loaded from Database for analysis:")
    print(crop.head()) # Display the first few rows

Attempting to connect to database for analysis...
Successfully connected to MySQL database
Executing query to fetch data...
Fetched 500 rows from database.
Converted results to Pandas DataFrame.
MySQL cursor closed.
MySQL connection closed.

DataFrame head loaded from Database for analysis:
    N   P   K temperature humidity    ph rainfall  crop_num
0  90  42  43       20.88    82.00  6.50   202.94         1
1  85  58  41       21.77    80.32  7.04   226.66         1
2  60  55  44       23.00    82.32  7.84   263.96         1
3  74  35  40       26.49    80.16  6.98   242.86         1
4  78  42  42       20.13    81.60  7.63   262.72         1


# Data Cleaning

In [14]:
crop.shape

(500, 8)

In [15]:
crop.info

<bound method DataFrame.info of       N   P   K temperature humidity    ph rainfall  crop_num
0    90  42  43       20.88    82.00  6.50   202.94         1
1    85  58  41       21.77    80.32  7.04   226.66         1
2    60  55  44       23.00    82.32  7.84   263.96         1
3    74  35  40       26.49    80.16  6.98   242.86         1
4    78  42  42       20.13    81.60  7.63   262.72         1
..   ..  ..  ..         ...      ...   ...      ...       ...
495   4  59  22       29.34    49.00  8.91    42.44        18
496  22  51  16       27.97    61.35  8.64    70.10        18
497  33  47  17       24.87    48.28  8.62    63.92        18
498   2  51  17       25.88    45.96  5.84    38.53        18
499  16  51  21       31.02    49.98  3.53    32.81        18

[500 rows x 8 columns]>

In [16]:
crop.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
crop_num       0
dtype: int64

In [17]:
crop.duplicated().sum()

np.int64(0)

In [18]:
crop.describe()

N           P           K    crop_num
count  500.000000  500.000000  500.000000  500.000000
mean    47.986000   55.912000   35.974000   12.400000
std     28.611589   12.336476   23.500593    8.966649
min      0.000000   35.000000   15.000000    1.000000
25%     24.000000   45.000000   19.000000    2.000000
50%     40.000000   56.000000   23.000000   18.000000
75%     74.000000   65.000000   42.000000   20.000000
max    100.000000   80.000000   85.000000   21.000000

In [20]:
crop

N   P   K temperature humidity    ph rainfall  crop_num
0    90  42  43       20.88    82.00  6.50   202.94         1
1    85  58  41       21.77    80.32  7.04   226.66         1
2    60  55  44       23.00    82.32  7.84   263.96         1
3    74  35  40       26.49    80.16  6.98   242.86         1
4    78  42  42       20.13    81.60  7.63   262.72         1
..   ..  ..  ..         ...      ...   ...      ...       ...
495   4  59  22       29.34    49.00  8.91    42.44        18
496  22  51  16       27.97    61.35  8.64    70.10        18
497  33  47  17       24.87    48.28  8.62    63.92        18
498   2  51  17       25.88    45.96  5.84    38.53        18
499  16  51  21       31.02    49.98  3.53    32.81        18

[500 rows x 8 columns]

# Train Test Split

In [23]:
X = crop.drop(['crop_num'],axis=1)
y = crop['crop_num']

In [24]:
X

N   P   K temperature humidity    ph rainfall
0    90  42  43       20.88    82.00  6.50   202.94
1    85  58  41       21.77    80.32  7.04   226.66
2    60  55  44       23.00    82.32  7.84   263.96
3    74  35  40       26.49    80.16  6.98   242.86
4    78  42  42       20.13    81.60  7.63   262.72
..   ..  ..  ..         ...      ...   ...      ...
495   4  59  22       29.34    49.00  8.91    42.44
496  22  51  16       27.97    61.35  8.64    70.10
497  33  47  17       24.87    48.28  8.62    63.92
498   2  51  17       25.88    45.96  5.84    38.53
499  16  51  21       31.02    49.98  3.53    32.81

[500 rows x 7 columns]

In [25]:
y

0       1
1       1
2       1
3       1
4       1
       ..
495    18
496    18
497    18
498    18
499    18
Name: crop_num, Length: 500, dtype: int64

In [26]:
y.shape

(500,)

In [30]:
!pip install scikit-learn
from sklearn.model_selection import train_test_split

     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     -------------------------------------- 60.8/60.8 kB 647.7 kB/s eta 0:00:00
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB 2.0 MB/s eta 0:00:06
   ---------------------------------------- 0.1/11.1 MB 1.4 MB/s eta 0:00:08
    --------------------------------------- 0.2/11.1 MB 1.3 MB/s eta 0:00:09
    --------------------------------------- 0.2/11.1 MB 1.4 MB/s eta 0:00:08
   - -------------------------------------- 0.3/11.1 MB 1.5 MB/s eta 0:00:08
   - -------------------------------------- 0.4/11.1 MB 1.5 MB/s eta 0:00:08
   - ----------------------------------


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\adity\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [32]:
X_train

N   P   K temperature humidity    ph rainfall
249  52  68  78       17.49    16.96  6.90    86.05
433   7  56  23       26.34    40.01  5.55    55.50
19   88  35  40       23.58    83.59  5.85   291.30
322  22  70  19       18.24    21.08  5.52    69.45
332  40  73  20       21.59    20.32  5.81    61.14
..   ..  ..  ..         ...      ...   ...      ...
106  93  41  17       25.62    66.50  6.05   105.47
270  42  74  83       19.26    14.28  7.55    65.78
348  34  60  23       20.13    24.97  5.66   100.05
435  11  45  19       28.70    44.36  3.83    44.12
102  80  43  16       23.56    71.59  6.66    66.72

[400 rows x 7 columns]


# Scale the features using MinMaxScaler

In [33]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()

X_train = ms.fit_transform(X_train)
X_test = ms.transform(X_test)

In [34]:
X_train

array([[0.52525253, 0.73333333, 0.9       , ..., 0.03818413, 0.52877138,
        0.20598565],
       [0.07070707, 0.46666667, 0.11428571, ..., 0.36416348, 0.31881804,
        0.09183978],
       [0.88888889, 0.        , 0.35714286, ..., 0.98048367, 0.36547434,
        0.97287401],
       ...,
       [0.34343434, 0.55555556, 0.11428571, ..., 0.15146373, 0.33592535,
        0.25829472],
       [0.11111111, 0.22222222, 0.05714286, ..., 0.42568236, 0.05132193,
        0.04931998],
       [0.80808081, 0.17777778, 0.01428571, ..., 0.81077641, 0.49144635,
        0.13376177]], shape=(400, 7))

# Training Models

In [35]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

# create instances of all models
models = {
    'Logistic Regression': LogisticRegression(),
    'Naive Bayes': GaussianNB(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Bagging': BaggingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'Extra Trees': ExtraTreeClassifier(),
}


for name, model in models.items():
    model.fit(X_train,y_train)
    ypred = model.predict(X_test)
    
    print(f"{name}  with accuracy : {accuracy_score(y_test,ypred)}")
    print("Confusion matrix : ",confusion_matrix(y_test,ypred))
    print("==========================================================")
    

Logistic Regression  with accuracy : 1.0
Confusion matrix :  [[28  0  0  0  0]
 [ 0 14  0  0  0]
 [ 0  0 24  0  0]
 [ 0  0  0 24  0]
 [ 0  0  0  0 10]]
Naive Bayes  with accuracy : 1.0
Confusion matrix :  [[28  0  0  0  0]
 [ 0 14  0  0  0]
 [ 0  0 24  0  0]
 [ 0  0  0 24  0]
 [ 0  0  0  0 10]]
Support Vector Machine  with accuracy : 1.0
Confusion matrix :  [[28  0  0  0  0]
 [ 0 14  0  0  0]
 [ 0  0 24  0  0]
 [ 0  0  0 24  0]
 [ 0  0  0  0 10]]
K-Nearest Neighbors  with accuracy : 1.0
Confusion matrix :  [[28  0  0  0  0]
 [ 0 14  0  0  0]
 [ 0  0 24  0  0]
 [ 0  0  0 24  0]
 [ 0  0  0  0 10]]
Decision Tree  with accuracy : 1.0
Confusion matrix :  [[28  0  0  0  0]
 [ 0 14  0  0  0]
 [ 0  0 24  0  0]
 [ 0  0  0 24  0]
 [ 0  0  0  0 10]]
Random Forest  with accuracy : 1.0
Confusion matrix :  [[28  0  0  0  0]
 [ 0 14  0  0  0]
 [ 0  0 24  0  0]
 [ 0  0  0 24  0]
 [ 0  0  0  0 10]]
Bagging  with accuracy : 1.0
Confusion matrix :  [[28  0  0  0  0]
 [ 0 14  0  0  0]
 [ 0  0 24  0  0]
 [

In [ ]:
# finally selected randomforest model
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
ypred = rfc.predict(X_test)
accuracy_score(y_test,ypred)

1.0

In [37]:
# or gausianjb
gnb = GaussianNB()
gnb.fit(X_train,y_train)
ypred = gnb.predict(X_test)
accuracy_score(y_test,ypred)

1.0

# Predictive System

In [38]:
def recommendation(N,P,k,temperature,humidity,ph,rainfal):
    features = np.array([[N,P,k,temperature,humidity,ph,rainfal]])
    transformed_features = ms.fit_transform(features)
    prediction = rfc.predict(transformed_features)
    print(prediction)
    return prediction[0] 

In [39]:
# new inputs


N = 40
P = 50
k = 50
temperature = 40.0
humidity = 20
ph = 100
rainfall = 100

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[20]
Kidneybeans is a best crop to be cultivated 


In [ ]:
# new inputs 2
N = 100
P = 90
k = 100
temperature = 50.0
humidity = 90.0
ph = 100
rainfall = 202.0

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[20]
Kidneybeans is a best crop to be cultivated 


In [41]:
# new inputs 2
N = 10
P = 10
k = 10
temperature = 15.0
humidity = 80.0
ph = 4.5
rainfall = 10.0

predict = recommendation(N,P,k,temperature,humidity,ph,rainfall)

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
                 8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
                 14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
                 19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}

if predict in crop_dict:
    crop = crop_dict[predict]
    print("{} is a best crop to be cultivated ".format(crop))
else:
    print("Sorry are not able to recommend a proper crop for this environment")

[20]
Kidneybeans is a best crop to be cultivated 


In [42]:
import pickle
pickle.dump(rfc,open('model.pkl','wb'))
pickle.dump(ms,open('minmaxscaler.pkl','wb'))

In [43]:

crop_dict = {1: "Rice", 2: "Maize", 3: "Jute", 4: "Cotton", 5: "Coconut", 6: "Papaya", 7: "Orange",
             8: "Apple", 9: "Muskmelon", 10: "Watermelon", 11: "Grapes", 12: "Mango", 13: "Banana",
             14: "Pomegranate", 15: "Lentil", 16: "Blackgram", 17: "Mungbean", 18: "Mothbeans",
             19: "Pigeonpeas", 20: "Kidneybeans", 21: "Chickpea", 22: "Coffee"}